### ISSUE TITLE
Fix Twinkle Twinkle Little Star

### ISSUE THREAD

**Issue by vanessaland** [vanessaland/cscu-github-demo#1]

**Comment by i-mah** [comment]
Twinkle, twinkle, little star, how I wonder what you are! Up above the world so high, like a diamond in the sky.

**Comment by jasonntruong** [comment]
Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.

**Comment by AbishananSriran** [comment]
Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, like a diamond in the sky. ⭐
