### ISSUE TITLE
Fix Single Ladies

### ISSUE THREAD

**Issue by vanessaland** [vanessaland/cscu-github-demo#2]

**Comment by winifred2412** [comment]
Now put your hands up Up in the clu-ub, we just broke up I'm ding my own little thin Decided to dip and now you wanna trip Cause another brother noticed me

**Comment by andraecari** [comment]
Now put ur hands up Up in the club, we just broke up I'm doing my own little thing Decided to dip and now you wanna trip Cause another brother noticed me

**Comment by i-mah** [comment]
Now put your hands up 
Up in the club, we just broke up I'm doing my own little thing 
Decided to dip and now you wanna trip 
Cause another brother noticed me

**Comment by jasonntruong** [comment]
Now put ur hands up
Up in the club, we just bro up
I'm dying my own little thing
Decided to dip and now you wanna trip
Cause another brother noticed me
