### ISSUE TITLE
Fix Old Town Road

### ISSUE THREAD

**Issue by vanessaland** [vanessaland/cscu-github-demo#3]

**Comment by thaothecow** [comment]
I got the horses in the back Horse tack is attached Hat is matte black Got the bots that's black to match Riding on a horse, ha You can whip ur Porch I been in the valley You ain't been up of the porch, now

**Comment by GuzhanLiang** [comment]
There is missing "Yeaaaaaah" at the beginning!

**Comment by jasonntruong** [comment]
I got the horses in the back
Horse tack is attached
Hat is matte black
Riding on a horse, ha
You can whip ur Porsche
I been in the valley
You ain't been up of the porch, now

**Comment by i-mah** [comment]
I got the horses in the back 
Horse tack is attached
Hat is matte black
Got the boots that's black to match
Riding on a horse, ha
You can whip your Porsche
I been in the valley
You ain't been up of the porch, now
