### ISSUE TITLE
Fix Hello

### ISSUE THREAD

**Issue by vanessaland** [vanessaland/cscu-github-demo#4]

**Comment by thaothecow** [comment]
Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky.

**Comment by itzmeppl** [comment]
Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky.

**Comment by HarmanSuri** [comment]
Hello, can you hear me? I'm in California dreaming about who we used to be When we were younger and free I've forgotten how it felt before the world fell at our feet

**Comment by alwaysindecisive** [comment]
Hello, can you hear me? I'm in California dreaming about who we used to be When we were younger and free I've forgotten how it felt before the world fell at our feet

**Comment by Bee0218** [comment]
Hello, can you h👂  me? I'm in California dreaming about who we used to be When we were younger and free I've forgotten how it felt before the 🌎  fell at our 🦶

**Comment by ca-bee** [comment]
Hello, can you hear me? I'm in California dreaming about who we used to be, When we were younger and free
I've forgotten how it felt before the world fell at our feet

**Comment by i-mah** [comment]
Hello, can you hear me?
I'm in Calfornia dreaming about who we used to be
When we were younger and free
I've forgotten how it felt before the world fell at our feet
